/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  // const projects = [
  //   {
  //     title: 'Documentation',
  //     description: 'Find in-depth information about Next.js features and API.',
  //     link: 'https://nextjs.org/docs',
  //   },
  //   {
  //     title: 'Documentation',
  //     description: 'Find in-depth information about Next.js features and API.',
  //     link: 'https://nextjs.org/docs',
  //   },
  //   {
  //     title: 'Documentation',
  //     description: 'Find in-depth information about Next.js features and API.',
  //     link: 'https://nextjs.org/docs',
  //   },
  //   {
  //     title: 'Documentation',
  //     description: 'Find in-depth information about Next.js features and API.',
  //     link: 'https://nextjs.org/docs',
  //   },
  // ]
    const projects = []

  return (
    <div className={styles.container}>
      <Head>
        <title>Enzo Bacqueyrisses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        👋 Hi I'm <a target="_blank" href="https://github.com/bacqueyrisses/" rel="noreferrer">Enzo Bacqueyrisses</a>
        </h1>

        <p className={styles.description}>
          Work in progress being a <code className={styles.code}>dEvElOpEr</code>
        </p>

        {projects.length > 0 && 
                <div className={styles.grid}>
                {projects.map((project, key) => (
                  <a key={key} href={project.link} className={styles.card}>
                  <h2>{project.title} &rarr;</h2>
                  <p>{project.description}</p>
                </a>
                ))}
              </div>
        }
        {projects.length == 0 && (
          <p style={{fontSize: '2rem'}}>No projects yet <span style={{marginLeft: '1rem'}}>🕳️</span></p>
        )
        }

      </main>

      <footer className={styles.footer}>
        <adiv
        >
          Made with 🍺
        </adiv>
      </footer>
    </div>
  )
}
